name: Notify PR

on: [pull_request]

env:
  SLACK_BOT_TOKEN: ${{ secrets.GS_SLACK_BOT_TOKEN }}

jobs:
  notify-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Say Hello
        uses: ./ # Uses an action in the root directory
        with:
          channel: '#interfaces'
          text: 'Test __using__ _markdown_ with [links](https://github.com/GoldenspearLLC/action-slack-post-message)'